spring:
  datasource:
    url: jdbc:sqlserver://localhost
    username: sa
    password: Password1!
    platform: mssql
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    database: SQL_SERVER
    show-sql: true